### PR TITLE
demo notebooks

### PR DESCRIPTION
**Pull request by clewis7**
my current thoughts are to split the notebooks as follows:

- [x] images
  - image updates
  - share controllers
  - manually creating a ipywidget slider
      - use simpler data (single plane zebra fish, imageio cockatoo)
  - image widget
- [x] line plots
  - fancy indexing (data, colors, cmaps)
  - line collections
- [x] interactivity
  - linear & linear region selectors
  - heatmaps
  - interactivity with both `link` and `add_event_handler`, image + contours
- [x] scatterplots
  - fancy indexing, brief, it's the same as lines
- [x] GridPlot

@kushalkolar let me know thoughts!

### CODE REVIEW

**Comment by clewis7** [comment]
can also do linear selectors with heatmaps!

**Comment by kushalkolar** [comment]
incorporate this into the first nb

image

**Comment by clewis7** [comment]
demo notebooks basically done, still TODO:

- [x] add heatmap with linear region selector to interactivity 
- [ ] zenodo upload of data (zebrafish file, contours, rcm, temporal)

was waiting for zenodo upload until after I get any changes you want me to make so that we only have to do it once!

**Comment by clewis7** [comment]
demo notebooks up-to-date with your earlier changes, can fix anything else you want tomorrow morning!

**Pull request merged**
